modLoader="javafml"
loaderVersion="${fml_range}"
license="GPL 3.0"
issueTrackerURL="https://github.com/rainweaver76/blockparty/issues/new/choose"

[[mods]]

modId="blockparty"
version="${version}"
displayName="Otterly's Blockparty"
logoFile="blockparty.png"
credits="A great deal of help from Thodor as well as unhealty amounts of caffiene."
authors="Otterly76"
description='''
All the pretty blocks!'''

[[dependencies.blockparty]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.blockparty]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version_range}, 1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.blockparty]]
modId="jei"
type="recommended"
versionRange="[${jei_version},)"
ordering="NONE"
side="BOTH"