modLoader="javafml"
loaderVersion="[2,)"
license="GPL 3.0"
issueTrackerURL="https://github.com/rainweaver76/blockparty/issues/new/choose"

[[mods]]

modId="blockparty"
version="1.0.0"
displayName="Otterly's Blockparty"
logoFile="blockparty.png"
credits="A great deal of help from Thodor as well as unhealty amounts of caffiene."
authors="Otterly76"
description='''
All the pretty blocks!'''

[[dependencies.blockparty]]
modId="neoforge"
type="required"
versionRange="[21.1.200,)"
ordering="NONE"
side="BOTH"

[[dependencies.blockparty]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"